import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  const [thoughts, setThoughts] = useState([]);
  const [title, setTitle] = useState("");
  const [newskeyword, setNewskeyword] = useState("");
  const [content, setContent] = useState("");

  useEffect(() => {
    axios.get('/api/thoughts')
      .then(response => {
        setThoughts(response.data);
      })
      .catch(error => {
        console.error(error);
      });
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const newThought = {
      title,
      newskeyword,
      content,
    };
    const res = await axios.post("/api/thoughts", newThought);
    setThoughts(prevThoughts => [...prevThoughts, res.data]);
    setTitle("");
    setNewskeyword("");
    setContent("");
  };


  useEffect(() => {
    axios.get('/api/thoughts/[thoughtid]/comments')
      .then(response => {
        setComment(response.data);
      })
      .catch(error => {
        console.error(error);
      });
  }, []);

  const handleComment = async (e, thought, comment) => {
    e.preventDefault();
    try {
      const response = await axios.post(`/api/thoughts/${thoughtid}/comments`, {
        content,
      });
      console.log(response.data);
      setContent("");
    } catch (error) {
      console.error(error);
    }
  };


  return (
    <>
      <Head>
        <title>Your THOUGHT on NEWS</title>
        <meta
          name="description"
          content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/favicon.ico" />
      </Head>

      <div className={`${styles.wrapper} ${styles.home_wrapper}`}>
        <h1 className={`${styles.home_page_ttl} ${styles.page_ttl}`}>
          Your THOUGHT on NEWS
        </h1>

        <main className={`${styles.main} ${styles.home_main}`}>

          <div className={styles.home_main_left}>
            <div className={styles.home_main_left_cont}>
              <h2 className={styles.home_main_left_cont_heading}>
                List of your thoughts
              </h2>

              {thoughts.map(thought => (
                <ThoughtComp
                  key={thought.id}
                  thought={thought}
                  handleComment={handleComment} />
              ))}
            </div>
          </div>

          <div className={styles.home_main_right}>
            <div className={styles.home_main_right_cont}>
              <h2 className={styles.home_main_right_cont_heading}>
                  Share your thought on NEWS
              </h2>

              <h3 className={styles.home_main_right_cont_formTtl}>
                Choose your news first
              </h3>

              <form
                onSubmit={handleSubmit}
                className={styles.home_main_right_cont_form}>

                <label className={styles.home_main_right_cont_form_label}>
                  News Title:
                  <input
                    className={styles.home_main_right_cont_form_label_input}
                    type="text"
                    placeholder='name'
                    value={title}
                    onChange={(e) => setTitle(e.target.value)} />
                </label>

                <label className={styles.home_main_right_cont_form_label}>
                  News Keyword:
                  <input
                    className={styles.home_main_right_cont_form_label_input}
                    type="text"
                    value={newskeyword}
                    onChange={(e) => setNewskeyword(e.target.value)} />
                </label>

                <label className={styles.home_main_right_cont_form_label}>
                  Details:
                  <input
                    className={`${styles.home_main_right_cont_form_label_input} ${styles.home_main_right_cont_form_label_inputDetails}`}
                    type="text"
                    value={content}
                    onChange={(e) => setContent(e.target.value)} />
                </label>

                <button
                  type="submit"
                  className={styles.btn}
                  id="btn">
                    Save Thought
                  <span></span><span></span><span></span><span></span>
                </button>

              </form>
            </div>
          </div>
        </main>

      </div>
    </>
  )
}

function ThoughtComp({thought, handleComment}) {
  const [comment, setComment] = useState("");
  const [comments, setComments] = useState([]);

  useEffect(() => {
    axios.get(`/api/thoughts/${thought.id}/comments`)
      .then(response => {
        setComments(response.data);
      })
      .catch(error => {
        console.error(error);
      });
  }, [thought.id]);

  return (
    <div className={styles.thoughtCont}>
      <div className={styles.postContainer}>
        <h2 className={styles.thoughtTitle}>
          {thought.title} <b>
          {thought.newskeyword}</b>
        </h2>
        <p className={styles.thoughtContent}>
          {thought.content}
        </p>
      </div>

      <form
        className={styles.thoughtCont_form}
        onSubmit={(e) => {
          e.preventDefault()
          handleComment(e, thought, comment)
        }}>
        <label className={styles.thoughtCont_form_label}>
          Comment:
          <input
            type="text"
            className={styles.thoughtCont_form_label_textarea}
            value={comment}
            onChange={(e) => setComment(e.target.value)} />
        </label>

        {/* <button
          type="submit"
          className={styles.btn}
          id="btn">
            Save Comment
          <span></span><span></span><span></span><span></span>
        </button> */}
        <button className={styles.commentButton} type="submit">Submit</button>
      </form>

      <ul className={styles.commentList}>
        {comments.map(comment => (
          <li
            key={comment.id}
            className={styles.commentItem}>- {comment.content}
          </li>
        ))}
      </ul>
    </div>
  );
}
